-- ============================================================
-- V10 (yashan) 合同管理增强 + 项目分工
--
-- 1) contract 表扩充"政府合同常见字段"：
--    合同类型 / 甲方 / 关键日期 / 合同状态 / 付款账户 / 验收标准 / 质保
--    说明：乙方沿用既有 vendor_name（供应商=承接单位），不再另设 party_b 以免字段冗余。
-- 2) 新增字典 CONTRACT_TYPE（合同类型）、CONTRACT_STATUS（合同状态）
-- 3) 新建 project_division 项目分工表（支持父子模块层级）
-- 4) 新增字典 DIVISION_STATUS（分工状态）
--
-- 约定（与既有迁移一致）：
--   * 主键 BIGINT GENERATED BY DEFAULT AS IDENTITY
--   * 字符列一律 VARCHAR(n CHAR)
--   * 索引在表外单独 CREATE INDEX
--   * 字典统一存 dict_item(dict_type, code, name, sort_no)；
--     配色不落库，在 frontend/src/config/tagDict.ts 里维护（见该文件 CONTRACT_TYPE_TAGS 等）
-- ============================================================

-- ── 1) 合同表扩充字段 ─────────────────────────────────────────
ALTER TABLE contract ADD (
    contract_type       VARCHAR(40 CHAR)   NULL,
    party_a             VARCHAR(128 CHAR)  NULL,
    sign_date           DATE               NULL,
    effective_date      DATE               NULL,
    start_date          DATE               NULL,
    end_date            DATE               NULL,
    contract_status     VARCHAR(40 CHAR)   NULL,
    payee_name          VARCHAR(128 CHAR)  NULL,
    payee_bank          VARCHAR(128 CHAR)  NULL,
    payee_account       VARCHAR(64 CHAR)   NULL,
    acceptance_standard VARCHAR(1000 CHAR) NULL,
    warranty_months     INT                NULL,
    warranty_amount     NUMBER(15,2)       NULL,
    settle_amount       NUMBER(15,2)       NULL
);

COMMENT ON COLUMN contract.contract_type       IS '合同类型(字典 CONTRACT_TYPE)：施工/第三方测评/方案评估/监理/设计/预算编制等';
COMMENT ON COLUMN contract.party_a             IS '甲方（建设单位/采购人）';
COMMENT ON COLUMN contract.sign_date           IS '签订日期';
COMMENT ON COLUMN contract.effective_date      IS '生效日期';
COMMENT ON COLUMN contract.start_date          IS '工期开始日期';
COMMENT ON COLUMN contract.end_date            IS '工期结束日期';
COMMENT ON COLUMN contract.contract_status     IS '合同状态(字典 CONTRACT_STATUS)';
COMMENT ON COLUMN contract.payee_name          IS '收款户名';
COMMENT ON COLUMN contract.payee_bank          IS '收款开户银行';
COMMENT ON COLUMN contract.payee_account       IS '收款银行账号';
COMMENT ON COLUMN contract.acceptance_standard IS '验收标准';
COMMENT ON COLUMN contract.warranty_months     IS '质保期（月）';
COMMENT ON COLUMN contract.warranty_amount     IS '质保金(元)';
COMMENT ON COLUMN contract.settle_amount       IS '结算金额(元)';

-- ── 2) 字典：合同类型 / 合同状态 ───────────────────────────────
INSERT INTO dict_item (dict_type, code, name, sort_no) VALUES ('CONTRACT_TYPE', 'MAIN',      '施工合同（主合同）', 1);
INSERT INTO dict_item (dict_type, code, name, sort_no) VALUES ('CONTRACT_TYPE', 'TEST',      '第三方测评', 2);
INSERT INTO dict_item (dict_type, code, name, sort_no) VALUES ('CONTRACT_TYPE', 'EVAL',      '方案评估', 3);
INSERT INTO dict_item (dict_type, code, name, sort_no) VALUES ('CONTRACT_TYPE', 'SUPERVISE', '监理服务', 4);
INSERT INTO dict_item (dict_type, code, name, sort_no) VALUES ('CONTRACT_TYPE', 'DESIGN',    '项目设计', 5);
INSERT INTO dict_item (dict_type, code, name, sort_no) VALUES ('CONTRACT_TYPE', 'BUDGET',    '预算编制', 6);
INSERT INTO dict_item (dict_type, code, name, sort_no) VALUES ('CONTRACT_TYPE', 'OTHER',     '其他', 99);

INSERT INTO dict_item (dict_type, code, name, sort_no) VALUES ('CONTRACT_STATUS', 'DRAFT',      '待签订', 1);
INSERT INTO dict_item (dict_type, code, name, sort_no) VALUES ('CONTRACT_STATUS', 'ACTIVE',     '履行中', 2);
INSERT INTO dict_item (dict_type, code, name, sort_no) VALUES ('CONTRACT_STATUS', 'DONE',       '已完成', 3);
INSERT INTO dict_item (dict_type, code, name, sort_no) VALUES ('CONTRACT_STATUS', 'CHANGED',    '已变更', 4);
INSERT INTO dict_item (dict_type, code, name, sort_no) VALUES ('CONTRACT_STATUS', 'TERMINATED', '已终止', 5);

-- ── 3) 项目分工表 ─────────────────────────────────────────────
-- 支持两级及以上：parent_id 为空是顶层模块，不为空是子模块。
-- 一份分工记录 = 一个"谁负责什么、什么时候做完、现在到哪一步"的条目。
CREATE TABLE project_division (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id       BIGINT           NOT NULL,
    parent_id        BIGINT           NULL,
    name             VARCHAR(128 CHAR) NOT NULL,
    owner_side       VARCHAR(20 CHAR)  NULL,
    owner_name       VARCHAR(64 CHAR)  NULL,
    vendor_owner     VARCHAR(64 CHAR)  NULL,
    plan_dev_date    DATE             NULL,
    plan_test_date   DATE             NULL,
    plan_online_date DATE             NULL,
    progress         INT              NOT NULL DEFAULT 0,
    status           VARCHAR(20 CHAR)  NULL,
    remark           VARCHAR(500 CHAR) NULL,
    sort_no          INT              NOT NULL DEFAULT 0,
    create_time      TIMESTAMP        NULL,
    update_time      TIMESTAMP        NULL,
    deleted          TINYINT          NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

COMMENT ON TABLE  project_division                  IS '项目分工（模块/子模块的负责方、负责人、计划时间与进度）';
COMMENT ON COLUMN project_division.id               IS '主键';
COMMENT ON COLUMN project_division.project_id       IS '所属项目（含子项目）';
COMMENT ON COLUMN project_division.parent_id        IS '父级分工 id（空=顶层模块）';
COMMENT ON COLUMN project_division.name             IS '模块/子模块名称';
COMMENT ON COLUMN project_division.owner_side       IS '负责方：OWNER 甲方 / VENDOR 乙方 / BOTH 双方';
COMMENT ON COLUMN project_division.owner_name       IS '甲方负责人';
COMMENT ON COLUMN project_division.vendor_owner     IS '乙方负责人';
COMMENT ON COLUMN project_division.plan_dev_date    IS '计划开发完成日期';
COMMENT ON COLUMN project_division.plan_test_date   IS '计划调试完成日期';
COMMENT ON COLUMN project_division.plan_online_date IS '计划上线日期';
COMMENT ON COLUMN project_division.progress         IS '当前进度（0-100）';
COMMENT ON COLUMN project_division.status           IS '状态(字典 DIVISION_STATUS)';
COMMENT ON COLUMN project_division.remark           IS '备注';
COMMENT ON COLUMN project_division.sort_no          IS '同级排序号';

CREATE INDEX idx_div_project ON project_division (project_id);
CREATE INDEX idx_div_parent  ON project_division (parent_id);

-- ── 4) 字典：分工状态 ─────────────────────────────────────────
INSERT INTO dict_item (dict_type, code, name, sort_no) VALUES ('DIVISION_STATUS', 'TODO',  '未开始', 1);
INSERT INTO dict_item (dict_type, code, name, sort_no) VALUES ('DIVISION_STATUS', 'DOING', '进行中', 2);
INSERT INTO dict_item (dict_type, code, name, sort_no) VALUES ('DIVISION_STATUS', 'DONE',  '已完成', 3);
INSERT INTO dict_item (dict_type, code, name, sort_no) VALUES ('DIVISION_STATUS', 'RISK',  '风险阻塞', 4);
