-- ============================================================
-- V11 (yashan) 资金情况「以付款为主线」+ 合同附件独立归属
--
-- 背景（功能职责重划分）：
--   * 资金情况：一条记录 = 一笔实际付款（含报销所需的付款过程信息）
--   * 合同管理：只管合同登记 + 合同相关附件（合同本身、法务意见、会签表…）
--   原先付款挂在合同折叠面板下展示，导致两个 tab 都在讲合同、彼此冗余。
--
-- 1) payment 表补"付款过程"字段：付款方式 / 经办人 / 发票号 / 记账凭证号 /
--    收款账户快照（合同账户可能变更，付款当时用的是哪个账户必须留痕）
-- 2) 新增字典 PAY_METHOD（付款方式）
-- 3) ATTACH_TYPE 扩充合同与付款常见类别（发票、付款审批单、法务意见书、
--    合同会签表、授权委托书、履约保函、合同变更协议）
-- 4) 新增字典 PAY_REQUIRED_ATTACH（报销/付款所需附件清单，用于界面缺件提醒；
--    做成字典便于在「系统管理→基础字典」自行调整要求）
-- 5) 历史附件归位：attach_type=CONTRACT 的附件原本挂在项目/阶段上，
--    统一改挂到 biz_type=CONTRACT + biz_id=合同id（合同多了以后必须能分辨属于哪份）
--
-- 约定（与既有迁移一致）：
--   * 主键 BIGINT GENERATED BY DEFAULT AS IDENTITY
--   * 字符列一律 VARCHAR(n CHAR)
--   * 索引在表外单独 CREATE INDEX
--   * 字典统一存 dict_item(dict_type, code, name, sort_no)，配色在
--     frontend/src/config/tagDict.ts 维护（不落库）
-- ============================================================

-- ── 1) 付款记录扩充字段 ───────────────────────────────────────
ALTER TABLE payment ADD (
    pay_method    VARCHAR(20 CHAR)  NULL,
    handler       VARCHAR(64 CHAR)  NULL,
    invoice_no    VARCHAR(64 CHAR)  NULL,
    voucher_no    VARCHAR(64 CHAR)  NULL,
    payee_name    VARCHAR(128 CHAR) NULL,
    payee_bank    VARCHAR(128 CHAR) NULL,
    payee_account VARCHAR(64 CHAR)  NULL
);

COMMENT ON COLUMN payment.pay_method    IS '付款方式(字典 PAY_METHOD)：银行转账/支票/汇票等';
COMMENT ON COLUMN payment.handler       IS '经办人';
COMMENT ON COLUMN payment.invoice_no    IS '发票号（可多张，此处记主要发票号）';
COMMENT ON COLUMN payment.voucher_no    IS '记账凭证号 / 报销单号';
COMMENT ON COLUMN payment.payee_name    IS '本次付款的收款户名（快照，付款当时核对用）';
COMMENT ON COLUMN payment.payee_bank    IS '本次付款的收款开户行（快照）';
COMMENT ON COLUMN payment.payee_account IS '本次付款的收款账号（快照）';

-- ── 2) 字典：付款方式 ─────────────────────────────────────────
INSERT INTO dict_item (dict_type, code, name, sort_no) VALUES ('PAY_METHOD', 'TRANSFER', '银行转账', 1);
INSERT INTO dict_item (dict_type, code, name, sort_no) VALUES ('PAY_METHOD', 'CHECK',    '支票',     2);
INSERT INTO dict_item (dict_type, code, name, sort_no) VALUES ('PAY_METHOD', 'DRAFT',    '银行汇票', 3);
INSERT INTO dict_item (dict_type, code, name, sort_no) VALUES ('PAY_METHOD', 'OFFSET',   '冲抵/抵扣', 4);
INSERT INTO dict_item (dict_type, code, name, sort_no) VALUES ('PAY_METHOD', 'OTHER',    '其他',     99);

-- ── 3) 字典：ATTACH_TYPE 扩充（合同侧 / 付款侧）────────────────
INSERT INTO dict_item (dict_type, code, name, sort_no) VALUES ('ATTACH_TYPE', 'INVOICE',          '发票',           16);
INSERT INTO dict_item (dict_type, code, name, sort_no) VALUES ('ATTACH_TYPE', 'PAY_APPROVAL',     '付款审批单',     17);
INSERT INTO dict_item (dict_type, code, name, sort_no) VALUES ('ATTACH_TYPE', 'LEGAL_OPINION',    '法务意见书',     18);
INSERT INTO dict_item (dict_type, code, name, sort_no) VALUES ('ATTACH_TYPE', 'COUNTERSIGN',      '合同会签表',     19);
INSERT INTO dict_item (dict_type, code, name, sort_no) VALUES ('ATTACH_TYPE', 'AUTHORIZATION',    '授权委托书',     20);
INSERT INTO dict_item (dict_type, code, name, sort_no) VALUES ('ATTACH_TYPE', 'PERFORMANCE_BOND', '履约保函',       21);
INSERT INTO dict_item (dict_type, code, name, sort_no) VALUES ('ATTACH_TYPE', 'CONTRACT_CHANGE',  '合同变更协议',   22);
INSERT INTO dict_item (dict_type, code, name, sort_no) VALUES ('ATTACH_TYPE', 'SUPPLIER_QUAL',    '供应商资质文件', 23);

-- ── 4) 字典：付款/报销所需附件清单 ────────────────────────────
-- code 取 ATTACH_TYPE 的 code，界面据此判断"是否已上传"；缺失时提示补件。
INSERT INTO dict_item (dict_type, code, name, sort_no) VALUES ('PAY_REQUIRED_ATTACH', 'PAY_APPROVAL', '付款审批单', 1);
INSERT INTO dict_item (dict_type, code, name, sort_no) VALUES ('PAY_REQUIRED_ATTACH', 'INVOICE',      '发票',       2);
INSERT INTO dict_item (dict_type, code, name, sort_no) VALUES ('PAY_REQUIRED_ATTACH', 'PAY_VOUCHER',  '付款凭证',   3);
INSERT INTO dict_item (dict_type, code, name, sort_no) VALUES ('PAY_REQUIRED_ATTACH', 'ACCEPT_REPORT','验收报告',   4);

-- ── 5) 合同附件归位：项目级 / 阶段级 → 合同级 ─────────────────
-- 5a) 项目级合同附件：biz_id(项目) → 该项目的合同 id
UPDATE attachment a
SET a.biz_id = (SELECT p.contract_id FROM project p WHERE p.id = a.biz_id AND ROWNUM = 1)
WHERE a.attach_type = 'CONTRACT'
  AND a.biz_type = 'PROJECT'
  AND EXISTS (SELECT 1 FROM project p WHERE p.id = a.biz_id AND p.contract_id IS NOT NULL);

UPDATE attachment a
SET a.biz_type = 'CONTRACT'
WHERE a.attach_type = 'CONTRACT'
  AND a.biz_type = 'PROJECT'
  AND EXISTS (SELECT 1 FROM contract c WHERE c.id = a.biz_id);

-- 5b) 阶段级合同附件：biz_id(阶段) → 阶段所属项目的合同 id
UPDATE attachment a
SET a.biz_id = (SELECT p.contract_id
                FROM project_phase ph, project p
                WHERE ph.id = a.biz_id AND p.id = ph.project_id AND ROWNUM = 1)
WHERE a.attach_type = 'CONTRACT'
  AND a.biz_type = 'PROJECT_PHASE'
  AND EXISTS (SELECT 1 FROM project_phase ph, project p
              WHERE ph.id = a.biz_id AND p.id = ph.project_id AND p.contract_id IS NOT NULL);

UPDATE attachment a
SET a.biz_type = 'CONTRACT'
WHERE a.attach_type = 'CONTRACT'
  AND a.biz_type = 'PROJECT_PHASE'
  AND EXISTS (SELECT 1 FROM contract c WHERE c.id = a.biz_id);

-- 5c) 归属类型注释更新（新增 CONTRACT）
COMMENT ON COLUMN attachment.biz_type IS '归属类型 PROJECT_PHASE(阶段)/PAYMENT(付款)/PROJECT(项目)/CONTRACT(合同)';

-- 说明：attachment 的 (biz_type, biz_id) 复合索引在 V1 已建（idx_attach_biz），
-- 此处**不再重复创建**——重复建会报 YAS-02043「columns have been indexed」。
-- 教训：迁移脚本里的 DDL 要先确认是否已存在（Oracle/yashan 的 DDL 隐式提交，失败重跑会留下中间态）。
