-- ============================================================
-- V12 (yashan) 项目 ↔ 合同 改为多对多关联表
--
-- 背景（修一个真实缺陷）：
--   原先"项目挂合同"靠 project.contract_id 这**一个指针**，导致
--   **一个项目只能有一份合同**——再登记第二份会覆盖指针，把上一份变成孤儿
--   （孤儿合同在下次删除项目时被 cleanupOrphanContracts 逻辑删除，数据会悄悄丢）。
--   而业务上（v1.5 起）明确：一个项目可签多份合同——施工主合同、监理服务、
--   第三方测评、预算编制、方案评估各自独立签订。
--
-- 方案：
--   1) 新建 project_contract 关联表作为**权威关联**（一个项目 N 份合同，一份合同 1 个项目）；
--   2) 回填历史：把现有 project.contract_id 写入关联表；
--   3) `project.contract_id` 字段**保留但语义收窄为「主合同」指针**
--      （由后端在保存合同时自动指向 MAIN 类型合同，无 MAIN 时取最早一份），
--      这样项目卡片/统计里"合同金额"等既有口径仍表示"主合同口径"，不必改一堆调用点。
--
-- 约定（与既有迁移一致）：
--   * 主键 BIGINT GENERATED BY DEFAULT AS IDENTITY
--   * 字符列 VARCHAR(n CHAR)；索引在表外单独 CREATE INDEX
--   * 建索引前先确认不重复（Oracle/yashan 的 DDL 隐式提交，
--     重复建索引会报 YAS-02043「columns have been indexed」，失败重跑会留下中间态）
-- ============================================================

-- ── 1) 项目-合同关联表 ────────────────────────────────────────
CREATE TABLE project_contract (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id  BIGINT    NOT NULL,
    contract_id BIGINT    NOT NULL,
    create_time TIMESTAMP NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE  project_contract             IS '项目↔合同关联（一个项目多份合同：施工主合同/监理/测评/预算编制…）';
COMMENT ON COLUMN project_contract.id          IS '主键';
COMMENT ON COLUMN project_contract.project_id  IS '项目（含子项目）id';
COMMENT ON COLUMN project_contract.contract_id IS '合同 id';
COMMENT ON COLUMN project_contract.create_time IS '关联建立时间';

CREATE INDEX idx_pc_project  ON project_contract (project_id);
CREATE INDEX idx_pc_contract ON project_contract (contract_id);

-- ── 2) 回填历史关联 ──────────────────────────────────────────
-- 注意：必须排除**已逻辑删除**的项目（project.deleted = 1），
-- 否则会给历史垃圾数据建关联，导致这些合同被误判为"仍被引用"而无法清理。
INSERT INTO project_contract (project_id, contract_id, create_time)
SELECT p.id, p.contract_id, CURRENT_TIMESTAMP
FROM project p
WHERE p.contract_id IS NOT NULL
  AND p.deleted = 0
  AND NOT EXISTS (SELECT 1 FROM project_contract pc
                  WHERE pc.project_id = p.id AND pc.contract_id = p.contract_id);
