-- ============================================================
-- V13 (yashan) 主系统 ↔ AI 能力服务 集成（P0 代理层）
--
-- 背景（见 docs/AI前端与集成方案.md §4.2 / §9）：
--   主系统前端只调主系统 /api/ai/*，由主系统做「权限 + 作用域解析 + 留痕」，
--   再代理到独立部署的 AI 能力服务（ai-backend，默认 8100）。
--   为此主系统需要三样持久化支撑：
--     1) 一条 AI 解析任务记录（谁触发的、进度、doc_id、失败原因）；
--     2) 附件上的「是否已可检索」状态（附件页/文档库要展示标签）；
--     3) 问答留痕（审计硬要求：谁、何时、问什么、作用域、引用数、耗时、是否降级）。
--
-- 三条边界（不在本迁移体现，但决定了下面的字段取舍）：
--   * 主系统是唯一事实源：这里只存「状态 + doc_id」，切片/向量等可重建物留在 AI 服务侧；
--   * 权限在主系统收口：作用域解析发生在主系统，故任务/留痕都带 project_id 与 user_id；
--   * AI 服务不直连主系统库：本表不由 AI 服务写入，全部由主系统代理层回写。
--
-- 约定（与 V1/V9/V12 一致）：
--   * 主键 BIGINT GENERATED BY DEFAULT AS IDENTITY
--   * 字符列 VARCHAR(n CHAR)；时间 TIMESTAMP；逻辑删除 deleted TINYINT DEFAULT 0
--   * 索引在表外单独 CREATE INDEX
--   * 幂等：迁移登记由 YashanMigrationRunner 负责（schema_version 表按文件名只跑一次），
--     与既有 V1~V12 相同，脚本内不做「列已存在则跳过」的方言判断
--     （崖山 Oracle 模式 ADD COLUMN 不支持 IF NOT EXISTS，写判断反而更不可靠）。
-- ============================================================

-- ── 1) AI 解析任务表 ──────────────────────────────────────────
-- 一行 = 一次「把某个附件送去 AI 服务解析入库」的尝试。
-- 重试会产生新行（保留历史），附件的最新状态以最新一行为准。
--
-- project_id / filename 是**刻意冗余**的：
--   * project_id 让任务列表能按项目过滤，且附件被删后任务历史仍可按项目追溯；
--   * filename 让「附件已被逻辑删除」时列表仍能显示当时的文件名（审计可读性）。
CREATE TABLE attachment_ai_task (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id    BIGINT           NULL,
    attachment_id BIGINT           NOT NULL,
    filename      VARCHAR(255 CHAR) NULL,
    status        VARCHAR(16 CHAR)  NOT NULL DEFAULT 'QUEUED',
    progress      INT              NOT NULL DEFAULT 0,
    ai_task_id    VARCHAR(64 CHAR)  NULL,
    doc_id        VARCHAR(64 CHAR)  NULL,
    error_msg     VARCHAR(500 CHAR) NULL,
    create_time   TIMESTAMP        NULL,
    update_time   TIMESTAMP        NULL,
    deleted       TINYINT          NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

COMMENT ON TABLE  attachment_ai_task              IS '附件→AI 服务解析任务（主系统侧记录，状态回写 attachment.ai_index_status；重试新增行保留历史）';
COMMENT ON COLUMN attachment_ai_task.id           IS '主键（对外即 §9 的 taskId）';
COMMENT ON COLUMN attachment_ai_task.project_id   IS '冗余：附件所属项目，便于按项目过滤与附件删除后追溯';
COMMENT ON COLUMN attachment_ai_task.attachment_id IS '主系统附件 id（attachment.id）';
COMMENT ON COLUMN attachment_ai_task.filename     IS '冗余：触发时的原始文件名（附件删除后仍可读）';
COMMENT ON COLUMN attachment_ai_task.status       IS '任务状态 QUEUED 排队中 / RUNNING 解析中 / DONE 已完成 / FAILED 失败（与 AI 服务的 QUEUED|PARSING|DONE|FAILED|CANCELLED 适配而来）';
COMMENT ON COLUMN attachment_ai_task.progress     IS '进度 0~100（AI 服务的阶段加权百分比，适配层取整）';
COMMENT ON COLUMN attachment_ai_task.ai_task_id   IS 'AI 服务的 upload-task id（用于轮询/重试对账，非必填）';
COMMENT ON COLUMN attachment_ai_task.doc_id       IS '解析入库后的 AI 文档 id（成功时才有）';
COMMENT ON COLUMN attachment_ai_task.error_msg    IS '失败原因（原样带出，不吞异常）';
COMMENT ON COLUMN attachment_ai_task.create_time  IS '触发时间（重试按此倒序取最新）';
COMMENT ON COLUMN attachment_ai_task.update_time  IS '最近一次状态回写时间';
COMMENT ON COLUMN attachment_ai_task.deleted      IS '逻辑删除 0 否 / 1 是';

CREATE INDEX idx_att_ai_task_attachment ON attachment_ai_task (attachment_id, create_time);
CREATE INDEX idx_att_ai_task_project    ON attachment_ai_task (project_id, create_time);
CREATE INDEX idx_att_ai_task_status     ON attachment_ai_task (status);
CREATE INDEX idx_att_ai_task_doc        ON attachment_ai_task (doc_id);

-- ── 2) attachment 增加 AI 索引相关列 ──────────────────────────
-- 全部可空且不设默认值：对存量数据零影响（历史附件读出来是 NULL，
-- 代码把 NULL 当作 NOT_PARSED 处理，见 Attachment.getAiIndexStatus 的使用处）。
ALTER TABLE attachment ADD (
    ai_index_status VARCHAR(16 CHAR)  NULL,
    ai_doc_id       VARCHAR(64 CHAR)  NULL,
    ai_indexed_at   TIMESTAMP         NULL
);

COMMENT ON COLUMN attachment.ai_index_status IS 'AI 可检索状态 NOT_PARSED 未解析 / PARSING 解析中 / READY 已可检索 / FAILED 解析失败；NULL 视同 NOT_PARSED';
COMMENT ON COLUMN attachment.ai_doc_id       IS 'AI 服务侧的文档 id（doc_id）；未解析/失败时为空';
COMMENT ON COLUMN attachment.ai_indexed_at   IS '最近一次解析成功入库时间';

-- ── 3) 问答留痕表 ─────────────────────────────────────────────
-- 审计硬要求：每次 /api/ai/chat 都要能回答「谁、何时、问什么、查了什么范围、
-- 引用了多少、花了多久、是否降级」。answer_digest 只存摘要（全文在响应里已给用户，
-- 留痕是为了追溯不是备份）。
CREATE TABLE ai_ask_log (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id        BIGINT           NULL,
    user_name      VARCHAR(64 CHAR)  NULL,
    question       VARCHAR(2000 CHAR) NOT NULL,
    project_id     BIGINT           NULL,
    attachment_ids VARCHAR(1000 CHAR) NULL,
    doc_ids        VARCHAR(2000 CHAR) NULL,
    cited_count    INT              NOT NULL DEFAULT 0,
    elapsed_ms     BIGINT           NOT NULL DEFAULT 0,
    degraded       TINYINT          NOT NULL DEFAULT 0,
    notice         VARCHAR(500 CHAR) NULL,
    answer_digest  VARCHAR(500 CHAR) NULL,
    create_time    TIMESTAMP        NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE  ai_ask_log                 IS 'AI 问答留痕（审计：谁/何时/问什么/作用域/引用数/耗时/是否降级）';
COMMENT ON COLUMN ai_ask_log.id              IS '主键（对外即 §9 的 logId）';
COMMENT ON COLUMN ai_ask_log.user_id         IS '提问用户 id（来自主系统登录态，不由前端传）';
COMMENT ON COLUMN ai_ask_log.user_name       IS '提问用户姓名（冗余，便于直接读日志）';
COMMENT ON COLUMN ai_ask_log.question        IS '用户原始问题（不截断）';
COMMENT ON COLUMN ai_ask_log.project_id      IS '作用域：项目 id（未限定时为空）';
COMMENT ON COLUMN ai_ask_log.attachment_ids  IS '作用域：用户指定的附件 id 列表（英文逗号分隔，未指定为空）';
COMMENT ON COLUMN ai_ask_log.doc_ids         IS '实际传给 AI 服务的 doc_id 列表（主系统解析后的最终范围，逗号分隔）';
COMMENT ON COLUMN ai_ask_log.cited_count     IS '答案里的引用条数';
COMMENT ON COLUMN ai_ask_log.elapsed_ms      IS '本次问答耗时（毫秒，含主系统作用域解析与 AI 服务调用）';
COMMENT ON COLUMN ai_ask_log.degraded        IS '是否降级（AI 服务报告向量检索不可用等）0 否 / 1 是';
COMMENT ON COLUMN ai_ask_log.notice          IS '降级/异常提示原文（与响应 notice 一致）';
COMMENT ON COLUMN ai_ask_log.answer_digest   IS '答案摘要（前 200 字，用于日志快速浏览）';
COMMENT ON COLUMN ai_ask_log.create_time     IS '提问时间';

CREATE INDEX idx_ai_ask_log_user    ON ai_ask_log (user_id, create_time);
CREATE INDEX idx_ai_ask_log_project ON ai_ask_log (project_id, create_time);
CREATE INDEX idx_ai_ask_log_time    ON ai_ask_log (create_time);
