-- ============================================================
-- V1 (yashan) 政府信息化项目管理系统 初始表结构
-- 由 MySQL 版 V1__init_schema.sql 按崖山 Oracle 模式方言转换：
--   * VARCHAR(n) -> VARCHAR(n CHAR)  按字符计数，避免中文按字节截断
--   * DATETIME    -> TIMESTAMP
--   * TEXT        -> CLOB
--   * DECIMAL(p,s)-> NUMBER(p,s)
--   * BIGINT AUTO_INCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--     （BY DEFAULT：历史数据迁移可显式带 id 导入）
--   * ENGINE/CHARSET/COLLATE 表尾选项移除，注释改 COMMENT ON TABLE/COLUMN
--   * 表内普通 KEY 索引拆为表外 CREATE INDEX（索引名需 schema 级唯一）
--   * 与 MySQL 版差异：project 的 idx_dept 不再建立（owner_dept_id 列
--     在 V3 被删除，该索引无终态意义）；sys_dept 表按历史脚本在 V3 删除。
-- ============================================================

-- 1. 用户
CREATE TABLE sys_user (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account         VARCHAR(64 CHAR)  NOT NULL,
    password        VARCHAR(100 CHAR) NOT NULL,
    name            VARCHAR(64 CHAR)  NOT NULL,
    dept_id         BIGINT            NULL,
    role            VARCHAR(20 CHAR)  NOT NULL DEFAULT 'MANAGER',
    status          TINYINT           NOT NULL DEFAULT 1,
    last_login_time TIMESTAMP         NULL,
    create_time     TIMESTAMP         NULL,
    update_time     TIMESTAMP         NULL,
    deleted         TINYINT           NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uk_account UNIQUE (account)
);
COMMENT ON TABLE  sys_user        IS '系统用户';
COMMENT ON COLUMN sys_user.id              IS '主键';
COMMENT ON COLUMN sys_user.account         IS '登录账号';
COMMENT ON COLUMN sys_user.password        IS 'BCrypt 密码哈希';
COMMENT ON COLUMN sys_user.name            IS '姓名';
COMMENT ON COLUMN sys_user.dept_id         IS '所属部门';
COMMENT ON COLUMN sys_user.role            IS '角色 ADMIN/MANAGER/VIEWER';
COMMENT ON COLUMN sys_user.status          IS '1启用 0停用';
COMMENT ON COLUMN sys_user.last_login_time IS '最后登录时间';

-- 2. 部门树（V3 将按历史脚本删除）
CREATE TABLE sys_dept (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    parent_id   BIGINT      NOT NULL DEFAULT 0,
    name        VARCHAR(64 CHAR) NOT NULL,
    order_no    INT         NOT NULL DEFAULT 0,
    create_time TIMESTAMP   NULL,
    update_time TIMESTAMP   NULL,
    deleted     TINYINT     NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
COMMENT ON TABLE  sys_dept       IS '部门';
COMMENT ON COLUMN sys_dept.id          IS '主键';
COMMENT ON COLUMN sys_dept.parent_id   IS '父部门，0为根';
COMMENT ON COLUMN sys_dept.name        IS '部门名称';

-- 3. 基础字典项
CREATE TABLE dict_item (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dict_type   VARCHAR(40 CHAR) NOT NULL,
    code        VARCHAR(40 CHAR) NOT NULL,
    name        VARCHAR(64 CHAR) NOT NULL,
    sort_no     INT         NOT NULL DEFAULT 0,
    create_time TIMESTAMP   NULL,
    update_time TIMESTAMP   NULL,
    deleted     TINYINT     NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
COMMENT ON TABLE  dict_item       IS '基础字典';
COMMENT ON COLUMN dict_item.id          IS '主键';
COMMENT ON COLUMN dict_item.dict_type   IS '字典类型编码';
COMMENT ON COLUMN dict_item.code        IS '字典项编码';
COMMENT ON COLUMN dict_item.name        IS '字典项名称';

-- 4. 阶段模板
CREATE TABLE phase_template (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_type       VARCHAR(10 CHAR)  NOT NULL,
    phase_name         VARCHAR(64 CHAR)  NOT NULL,
    sort_no            INT               NOT NULL DEFAULT 0,
    weight             INT               NOT NULL DEFAULT 0,
    pay_node           VARCHAR(20 CHAR)  NULL,
    description        VARCHAR(255 CHAR) NULL,
    attach_type_hints  VARCHAR(255 CHAR) NULL,
    skipable           TINYINT           NOT NULL DEFAULT 0,
    create_time        TIMESTAMP         NULL,
    update_time        TIMESTAMP         NULL,
    deleted            TINYINT           NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
COMMENT ON TABLE  phase_template       IS '阶段模板';
COMMENT ON COLUMN phase_template.id                 IS '主键';
COMMENT ON COLUMN phase_template.project_type       IS '项目类型 HW硬件/SW软件';
COMMENT ON COLUMN phase_template.phase_name         IS '阶段名称';
COMMENT ON COLUMN phase_template.sort_no            IS '顺序';
COMMENT ON COLUMN phase_template.weight             IS '默认权重(用于整体进度)';
COMMENT ON COLUMN phase_template.pay_node           IS '里程碑付款节点编码(可空)';
COMMENT ON COLUMN phase_template.description        IS '主要工作/判定标准';
COMMENT ON COLUMN phase_template.attach_type_hints  IS '常用附件类别提示(逗号分隔)';
COMMENT ON COLUMN phase_template.skipable           IS '是否允许跳过';

-- 5. 项目主档
CREATE TABLE project (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code               VARCHAR(64 CHAR)   NOT NULL,
    name               VARCHAR(128 CHAR)  NOT NULL,
    type               VARCHAR(10 CHAR)   NOT NULL,
    status             VARCHAR(10 CHAR)   NOT NULL DEFAULT 'RUN',
    owner_unit         VARCHAR(64 CHAR)   NULL,
    owner_dept_id      BIGINT             NULL,
    manager_user_id    BIGINT             NULL,
    member_ids         VARCHAR(255 CHAR)  NULL,
    vendor_name        VARCHAR(128 CHAR)  NULL,
    vendor_contact     VARCHAR(128 CHAR)  NULL,
    approve_no         VARCHAR(64 CHAR)   NULL,
    budget_amount      NUMBER(15,2)       NULL,
    fund_source        VARCHAR(40 CHAR)   NULL,
    bid_type           VARCHAR(40 CHAR)   NULL,
    bid_amount         NUMBER(15,2)       NULL,
    contract_no        VARCHAR(64 CHAR)   NULL,
    contract_amount    NUMBER(15,2)       NULL,
    change_amount      NUMBER(15,2)       NOT NULL DEFAULT 0,
    approve_date       DATE               NULL,
    plan_start_date    DATE               NULL,
    plan_finish_date   DATE               NULL,
    actual_finish_date DATE               NULL,
    content_summary    CLOB               NULL,
    project_source     VARCHAR(40 CHAR)   NULL,
    remark             VARCHAR(500 CHAR)  NULL,
    create_by          BIGINT             NULL,
    create_time        TIMESTAMP          NULL,
    update_time        TIMESTAMP          NULL,
    deleted            TINYINT            NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uk_code UNIQUE (code)
);
COMMENT ON TABLE  project       IS '项目主档';
COMMENT ON COLUMN project.id                 IS '主键';
COMMENT ON COLUMN project.code               IS '项目编号';
COMMENT ON COLUMN project.name               IS '项目名称';
COMMENT ON COLUMN project.type               IS 'HW/SW';
COMMENT ON COLUMN project.status             IS 'RUN/DONE/PAUSE/STOP';
COMMENT ON COLUMN project.owner_unit         IS '甲方单位(字典名称快照)';
COMMENT ON COLUMN project.owner_dept_id      IS '甲方内部承接部门(V3删除)';
COMMENT ON COLUMN project.manager_user_id    IS '项目经理(内部负责人)';
COMMENT ON COLUMN project.member_ids         IS '参与人员id(逗号分隔)';
COMMENT ON COLUMN project.vendor_name        IS '供应商全称';
COMMENT ON COLUMN project.vendor_contact     IS '供应商联系人姓名/电话';
COMMENT ON COLUMN project.approve_no         IS '批复文号';
COMMENT ON COLUMN project.budget_amount      IS '概算/预算金额(元)';
COMMENT ON COLUMN project.fund_source        IS '资金来源(字典code)';
COMMENT ON COLUMN project.bid_type           IS '招标方式(字典code)';
COMMENT ON COLUMN project.bid_amount         IS '中标金额';
COMMENT ON COLUMN project.contract_no        IS '合同编号';
COMMENT ON COLUMN project.contract_amount    IS '合同金额';
COMMENT ON COLUMN project.change_amount      IS '变更金额(+/-)';
COMMENT ON COLUMN project.approve_date       IS '立项/批复日期';
COMMENT ON COLUMN project.actual_finish_date IS '实际完成(终验)日期';
COMMENT ON COLUMN project.content_summary    IS '建设内容摘要';
COMMENT ON COLUMN project.project_source     IS '项目来源(字典code)';

-- 6. 项目阶段实例
CREATE TABLE project_phase (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id         BIGINT       NOT NULL,
    phase_name         VARCHAR(64 CHAR)  NOT NULL,
    sort_no            INT          NOT NULL DEFAULT 0,
    weight             INT          NOT NULL DEFAULT 0,
    pay_node           VARCHAR(20 CHAR)  NULL,
    status             VARCHAR(20 CHAR)  NOT NULL DEFAULT 'NOT_STARTED',
    percent            INT          NOT NULL DEFAULT 0,
    plan_start_date    DATE         NULL,
    plan_finish_date   DATE         NULL,
    actual_start_date  DATE         NULL,
    actual_finish_date DATE         NULL,
    manager_user_id    BIGINT       NULL,
    note               CLOB         NULL,
    result_fields      CLOB         NULL,
    create_time        TIMESTAMP    NULL,
    update_time        TIMESTAMP    NULL,
    deleted            TINYINT      NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
COMMENT ON TABLE  project_phase       IS '项目阶段实例';
COMMENT ON COLUMN project_phase.project_id         IS '项目id';
COMMENT ON COLUMN project_phase.phase_name         IS '阶段名称(快照)';
COMMENT ON COLUMN project_phase.weight             IS '权重(快照)';
COMMENT ON COLUMN project_phase.status             IS 'NOT_STARTED/IN_PROGRESS/DONE/SKIPPED';
COMMENT ON COLUMN project_phase.percent            IS '完成比例0-100';
COMMENT ON COLUMN project_phase.manager_user_id    IS '阶段负责人';
COMMENT ON COLUMN project_phase.note               IS '经办记录/说明';
COMMENT ON COLUMN project_phase.result_fields      IS '阶段关键结果字段(JSON)';

-- 7. 附件
CREATE TABLE attachment (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    biz_type       VARCHAR(20 CHAR)  NOT NULL,
    biz_id         BIGINT           NOT NULL,
    attach_type    VARCHAR(40 CHAR)  NULL,
    file_name      VARCHAR(255 CHAR) NOT NULL,
    stored_name    VARCHAR(64 CHAR)  NOT NULL,
    file_path      VARCHAR(255 CHAR) NOT NULL,
    file_size      BIGINT           NOT NULL DEFAULT 0,
    file_ext       VARCHAR(16 CHAR)  NULL,
    upload_user_id BIGINT           NULL,
    upload_time    TIMESTAMP        NULL,
    deleted        TINYINT          NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
COMMENT ON TABLE  attachment       IS '附件';
COMMENT ON COLUMN attachment.id             IS '主键';
COMMENT ON COLUMN attachment.biz_type       IS '归属类型 PROJECT_PHASE/PAYMENT/PROJECT';
COMMENT ON COLUMN attachment.biz_id         IS '归属业务id';
COMMENT ON COLUMN attachment.attach_type    IS '文档类别(字典code)';
COMMENT ON COLUMN attachment.file_name      IS '原始文件名';
COMMENT ON COLUMN attachment.stored_name    IS '存储文件名(uuid.扩展名)';
COMMENT ON COLUMN attachment.file_path      IS '相对上传目录路径';
COMMENT ON COLUMN attachment.file_size      IS '字节';
COMMENT ON COLUMN attachment.upload_user_id IS '上传用户id';
COMMENT ON COLUMN attachment.upload_time    IS '上传时间';

-- 8. 付款记录
CREATE TABLE payment (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id     BIGINT        NOT NULL,
    node_code      VARCHAR(20 CHAR)   NOT NULL,
    node_name      VARCHAR(64 CHAR)   NOT NULL,
    condition_desc VARCHAR(255 CHAR)  NULL,
    plan_amount    NUMBER(15,2)       NULL,
    plan_date      DATE               NULL,
    paid_amount    NUMBER(15,2)       NOT NULL DEFAULT 0,
    paid_date      DATE               NULL,
    status         VARCHAR(10 CHAR)   NOT NULL DEFAULT 'UNPAID',
    remark         VARCHAR(500 CHAR)  NULL,
    create_time    TIMESTAMP          NULL,
    update_time    TIMESTAMP          NULL,
    deleted        TINYINT            NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
COMMENT ON TABLE  payment       IS '付款记录';
COMMENT ON COLUMN payment.id             IS '主键';
COMMENT ON COLUMN payment.project_id     IS '项目id';
COMMENT ON COLUMN payment.node_code      IS '付款节点编码 PREPAY/ARRIVAL/FIRST_ACCEPT/FINAL_ACCEPT/WARRANTY';
COMMENT ON COLUMN payment.condition_desc IS '触发条件';
COMMENT ON COLUMN payment.plan_amount    IS '计划金额';
COMMENT ON COLUMN payment.plan_date      IS '计划付款日期';
COMMENT ON COLUMN payment.paid_amount    IS '实付金额';
COMMENT ON COLUMN payment.status         IS 'UNPAID/PART/PAID';

-- 9. 操作日志（只追加，不删除）
CREATE TABLE operate_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT       NULL,
    user_name   VARCHAR(64 CHAR)  NULL,
    biz_type    VARCHAR(30 CHAR)  NOT NULL,
    biz_id      BIGINT       NULL,
    action      VARCHAR(40 CHAR)  NOT NULL,
    detail      VARCHAR(500 CHAR) NULL,
    create_time TIMESTAMP    NULL,
    PRIMARY KEY (id)
);
COMMENT ON TABLE  operate_log       IS '操作日志';
COMMENT ON COLUMN operate_log.biz_type    IS 'PROJECT/PHASE/ATTACHMENT/PAYMENT/USER/LOGIN';
COMMENT ON COLUMN operate_log.action      IS 'CREATE/UPDATE/DELETE/UPLOAD/DOWNLOAD/LOGIN...';
COMMENT ON COLUMN operate_log.detail      IS '操作描述';

-- ============ 普通索引（原表内 KEY，拆出并全局唯一命名） ============
CREATE INDEX idx_dict_type      ON dict_item (dict_type, sort_no);
CREATE INDEX idx_pt_type_sort   ON phase_template (project_type, sort_no);
CREATE INDEX idx_proj_type_status ON project (type, status);
CREATE INDEX idx_proj_manager   ON project (manager_user_id);
CREATE INDEX idx_proj_name      ON project (name);
CREATE INDEX idx_pphase_project ON project_phase (project_id, sort_no);
CREATE INDEX idx_attach_biz     ON attachment (biz_type, biz_id);
CREATE INDEX idx_attach_type    ON attachment (attach_type);
CREATE INDEX idx_pay_project    ON payment (project_id);
CREATE INDEX idx_log_biz        ON operate_log (biz_type, biz_id);
CREATE INDEX idx_log_time       ON operate_log (create_time);
