-- ============================================================
-- V4 (yashan) 项目-子项目体系 与 合同(可覆盖多个子项目) 模型
-- 由 MySQL 版 V4__project_children_contract.sql 转换：
--   * ALTER ... ADD COLUMN ..., ADD KEY ... 拆为 ADD 列 + 表外 CREATE INDEX
--   * MySQL UPDATE t JOIN ... 改写为 Oracle 相关标量子查询 + ROWNUM=1
--   * 回填语句对全新空库执行影响 0 行，仅保留语义等价
-- ============================================================

-- 1) 父子层级
ALTER TABLE project ADD (parent_id BIGINT NULL);
CREATE INDEX idx_proj_parent ON project (parent_id);

-- 2) 合同表
CREATE TABLE contract (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(128 CHAR)  NOT NULL,
    contract_no     VARCHAR(64 CHAR)   NULL,
    vendor_name     VARCHAR(128 CHAR)  NULL,
    vendor_contact  VARCHAR(128 CHAR)  NULL,
    bid_type        VARCHAR(40 CHAR)   NULL,
    bid_amount      NUMBER(15,2)       NULL,
    contract_amount NUMBER(15,2)       NULL,
    change_amount   NUMBER(15,2)       NOT NULL DEFAULT 0,
    plan_amount     NUMBER(15,2)       NULL,
    scope_remark    VARCHAR(500 CHAR)  NULL,
    remark          VARCHAR(500 CHAR)  NULL,
    create_time     TIMESTAMP          NULL,
    update_time     TIMESTAMP          NULL,
    deleted         TINYINT            NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
COMMENT ON TABLE  contract       IS '合同（可覆盖一个或多个项目/子项目）';
COMMENT ON COLUMN contract.id              IS '主键';
COMMENT ON COLUMN contract.name            IS '合同名称（建议含总项目/子项目说明）';
COMMENT ON COLUMN contract.contract_no     IS '合同编号';
COMMENT ON COLUMN contract.vendor_name     IS '供应商';
COMMENT ON COLUMN contract.contract_amount IS '合同金额(元)';
COMMENT ON COLUMN contract.change_amount   IS '变更金额(+/-)';
COMMENT ON COLUMN contract.plan_amount     IS '计划(合同总额口径预留)';
COMMENT ON COLUMN contract.scope_remark    IS '覆盖范围说明，如：覆盖 3 个子项目';
CREATE INDEX idx_contract_no ON contract (contract_no);

-- 3) 项目挂合同
ALTER TABLE project ADD (contract_id BIGINT NULL);
CREATE INDEX idx_proj_contract ON project (contract_id);

-- 4) 付款挂合同
ALTER TABLE payment ADD (contract_id BIGINT NULL);
CREATE INDEX idx_pay_contract ON payment (contract_id);

-- ============ 回填（对历史数据幂等、仅本地演示数据有意义） ============

-- 4a) 为"有合同编号或合同金额"的历史项目生成合同
INSERT INTO contract (name, contract_no, vendor_name, vendor_contact, bid_type, bid_amount,
                      contract_amount, change_amount, remark)
SELECT p.name, p.contract_no, p.vendor_name, p.vendor_contact, p.bid_type, p.bid_amount,
       p.contract_amount, COALESCE(p.change_amount, 0), '由历史项目数据迁移生成'
FROM project p
WHERE (p.contract_no IS NOT NULL OR p.contract_amount IS NOT NULL)
  AND NOT EXISTS (SELECT 1 FROM contract c WHERE c.contract_no = p.contract_no AND p.contract_no IS NOT NULL);

-- 4b) 回填 project.contract_id（优先按合同编号匹配）
UPDATE project p
SET p.contract_id = (SELECT c.id FROM contract c
                     WHERE c.contract_no = p.contract_no AND ROWNUM = 1)
WHERE p.contract_no IS NOT NULL
  AND p.contract_id IS NULL;

-- 4c) 兜底：无合同编号但有金额的，按项目名匹配（演示数据名唯一）
UPDATE project p
SET p.contract_id = (SELECT c.id FROM contract c
                     WHERE c.name = p.name AND c.contract_no IS NULL AND ROWNUM = 1)
WHERE p.contract_no IS NULL
  AND p.contract_amount IS NOT NULL
  AND p.contract_id IS NULL;

-- 4d) 付款记录挂接到其项目所属合同
UPDATE payment pa
SET pa.contract_id = (SELECT p.contract_id FROM project p
                      WHERE p.id = pa.project_id AND ROWNUM = 1)
WHERE pa.contract_id IS NULL;
