-- ============================================================
-- V6 (yashan)：项目概览（类 README 介绍 + 二级功能模块清单）
-- 一个项目一行；intro_md 存 Markdown；modules_json 存二级清单 JSON：
--   [{ "name":"模块", "description":"说明", "children":[{"name":"子模块","description":""}] }]
-- 转换说明：TEXT -> CLOB；DATETIME -> TIMESTAMP；表内 UNIQUE KEY 保留为约束。
-- ============================================================
CREATE TABLE project_overview (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id   BIGINT        NOT NULL,
    intro_md     CLOB          NULL,
    modules_json CLOB          NULL,
    create_time  TIMESTAMP     NULL,
    update_time  TIMESTAMP     NULL,
    deleted      TINYINT       NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uk_overview_project UNIQUE (project_id)
);
COMMENT ON TABLE  project_overview IS '项目概览：README 式介绍 + 功能模块清单';
COMMENT ON COLUMN project_overview.project_id   IS '项目 id';
COMMENT ON COLUMN project_overview.intro_md     IS '项目介绍（Markdown，项目背景/用途/功能概览/应用场景）';
COMMENT ON COLUMN project_overview.modules_json IS '功能模块清单（二级 JSON）';
