-- ============================================================
-- V7 (yashan)：流程模板（多套模板：Tab 式管理）
-- phase_tpl = 模板（每套模板一个分组）；phase_template 增加 tpl_id 归属。
-- 转换说明：ALTER ADD 列 + 表外 CREATE INDEX 拆分；
--           MySQL 多行 VALUES 拆为逐行 INSERT；
--           UPDATE ... SET (SELECT...) 相关子查询改写保持 Oracle 语义。
-- ============================================================
CREATE TABLE phase_tpl (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_type VARCHAR(16 CHAR) NOT NULL,
    name         VARCHAR(64 CHAR) NOT NULL,
    builtin      TINYINT      NOT NULL DEFAULT 0,
    is_default   TINYINT      NOT NULL DEFAULT 0,
    enabled      TINYINT      NOT NULL DEFAULT 1,
    sort_no      INT          NOT NULL DEFAULT 0,
    remark       VARCHAR(255 CHAR) NULL,
    create_time  TIMESTAMP    NULL,
    update_time  TIMESTAMP    NULL,
    deleted      TINYINT      NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
COMMENT ON TABLE  phase_tpl IS '流程模板（多套，含内置默认模板）';
COMMENT ON COLUMN phase_tpl.project_type IS 'HW/SW';
COMMENT ON COLUMN phase_tpl.name         IS '模板名称';
COMMENT ON COLUMN phase_tpl.builtin      IS '是否内置（内置不可删除）';
COMMENT ON COLUMN phase_tpl.is_default   IS '是否类型默认模板（新建项目使用）';
COMMENT ON COLUMN phase_tpl.enabled      IS '启用';
COMMENT ON COLUMN phase_tpl.sort_no      IS '展示排序';
CREATE INDEX idx_tpl_type ON phase_tpl (project_type);

ALTER TABLE phase_template ADD (tpl_id BIGINT NULL);
CREATE INDEX idx_pt_tpl ON phase_template (tpl_id);

-- 内置默认模板
INSERT INTO phase_tpl (project_type, name, builtin, is_default, enabled, sort_no, remark)
VALUES ('HW', '硬件项目默认模板', 1, 1, 1, 1, '系统内置：硬件 9 阶段');
INSERT INTO phase_tpl (project_type, name, builtin, is_default, enabled, sort_no, remark)
VALUES ('SW', '软件项目默认模板', 1, 1, 1, 2, '系统内置：软件 11 阶段');

-- 回填阶段归属
UPDATE phase_template SET tpl_id = (SELECT id FROM phase_tpl WHERE project_type = 'HW' AND builtin = 1)
WHERE project_type = 'HW' AND (tpl_id IS NULL OR deleted = 0);
UPDATE phase_template SET tpl_id = (SELECT id FROM phase_tpl WHERE project_type = 'SW' AND builtin = 1)
WHERE project_type = 'SW' AND (tpl_id IS NULL OR deleted = 0);
