-- ============================================================
-- V9 (yashan)：附件后台上传任务表 attachment_upload_task
--
-- 背景：大文件同步写 OBS 易超时（nginx proxy_read_timeout / 客户端 socketTimeout 默认 60s）。
-- 改为「先落本地临时区 → 立即返回任务ID → 后台线程推送 OBS」，
-- 本表即上传记录：前端据此展示进度（轮询）与历史上传状态。
--
-- status 取值：PENDING(已受理) / UPLOADING(推送存储中) / SUCCESS / FAILED
-- 转换说明：与 V1 一致，主键用 IDENTITY；VARCHAR 标 CHAR 语义；时间用 TIMESTAMP。
-- ============================================================
CREATE TABLE attachment_upload_task (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id     BIGINT           NULL,
    biz_type       VARCHAR(20 CHAR)  NOT NULL,
    biz_id         BIGINT           NOT NULL,
    attach_type    VARCHAR(40 CHAR)  NULL,
    file_name      VARCHAR(255 CHAR) NOT NULL,
    file_size      BIGINT           NOT NULL DEFAULT 0,
    file_ext       VARCHAR(16 CHAR)  NULL,
    stored_name    VARCHAR(64 CHAR)  NULL,
    file_path      VARCHAR(255 CHAR) NULL,
    temp_path      VARCHAR(255 CHAR) NULL,
    status         VARCHAR(16 CHAR)  NOT NULL DEFAULT 'PENDING',
    progress       INT              NOT NULL DEFAULT 0,
    error_msg      VARCHAR(500 CHAR) NULL,
    attachment_id  BIGINT           NULL,
    upload_user_id BIGINT           NULL,
    create_time    TIMESTAMP        NULL,
    finish_time    TIMESTAMP        NULL,
    deleted        TINYINT          NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

CREATE INDEX idx_att_upload_task_project ON attachment_upload_task (project_id, create_time);
CREATE INDEX idx_att_upload_task_status  ON attachment_upload_task (status);
